//
//  Academic License - for use in teaching, academic research, and meeting
//  course requirements at degree granting institutions only.  Not for
//  government, commercial, or other organizational use.
//
//  surf_fcn.cpp
//
//  Code generation for function 'surf_fcn'
//


// Include files
#include "surf_fcn.h"
#include <cmath>

// Function Definitions
void surf_fcn(double x, double y, double out1[4])
{
  double t6;
  double t7;
  double t8;
  double t9;

  // SURF_FCN
  //     OUT1 = SURF_FCN(X,Y)
  //     This function was generated by the Symbolic Math Toolbox version 8.6.
  //     11-Nov-2020 18:38:08
  t6 = x * 3.1415926535897931 * 0.01131520805242602 + 1.430782006706746;
  t7 = y * 3.1415926535897931 * 0.01155275839956154 - 0.330436466696244;
  t8 = y * 3.1415926535897931 * 0.011722983884281351 + 0.48399372981007471;
  t9 = x * 3.1415926535897931 * 0.012272243234298191 - 0.29309335149430982;
  out1[0] = ((std::sin(t6) * 2.0214791347992 + std::sin(t7) * 2.2321880997147412)
             - std::sin(t8) * 1.274556347098621) + std::sin(t9) *
    4.7015322203620276;
  out1[1] = 3.1415926535897931 * std::cos(t6) * 0.02287345698389108 +
    3.1415926535897931 * std::cos(t9) * 0.05769834698217282;
  out1[2] = 3.1415926535897931 * std::cos(t7) * 0.0257879298183808 -
    3.1415926535897931 * std::cos(t8) * 0.01494160351664563;
  out1[3] = 1.0;
}

// End of code generation (surf_fcn.cpp)
